version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Check Node.js version
          command: node -v
      - run:
          name: Install yarn to latest version
          command: 'curl -o- -L https://yarnpkg.com/install.sh | bash'
      - restore_cache:
          name: Restore dependencies from cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies if needed
          command: |
            if [ ! -d node_modules ]; then
              yarn install --frozen-lockfile
            fi
      - save_cache:
          name: Cache dependencies
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn eslint . --quiet
      - run:
          name: Test
          command: yarn jest --ci --maxWorkers=2
      - run:
          name: Build
          command: npm run build
